name = input("What is your name? ")
print( "Hello"+" "  + name)
ID= input("What is your Student ID?")
print("Your ID is"+" " + ID)
var1 = input("Enter a number for first variable ")
var2 = input("Enter a number for second variable ")
sum = int(var1) + int(var2)
diff = int(var1) - int(var2)
prod = int(var1) * int(var2)
print("Summation of these two numbers are " , int(sum))
print("Difference of these two numbers are " , int(diff))
print("Result of multiplication of these two numbers are ", int(prod))


name2 = input("What is your name? ")
labgrade = input("Enter your lab grade")
midgrade = input("Enter your midterm grade")
finalgrade = input("Enter your final grade")
lastscore = float((int(labgrade)*float(0.25))+ (int(midgrade)*float(0.35)) + (int(finalgrade)*float(0.4)))
print("Lab Grade: " , labgrade)
print("Midterm Grade: " , midgrade)
print("Final Grade: " , finalgrade)
print("Last Score: " , lastscore)

print('*\n**\n***\n***\n**\n*' )
